name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint, Build
        run: npx nx run-many -t lint build --exclude=e2e

      - name: Fix CI (if needed)
        if: failure()
        run: npx nx fix-ci

      - name: Upload dist as artifact (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup Git user for deploy
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy 